### ISSUE TITLE
no appicon image on appimage

### ISSUE THREAD

**Issue by RAVENz46** [jlpatter/oxidized_git#335]
I installed it on some distro(nixos, popos) via appimage and confirmed that desktop icon was created but no image.

**Comment by jlpatter** [comment]
@RAVENz46 Hey, I appreciate you taking an interest in Oxidized Git! Unfortunately, I haven't had too much time to work on the project recently, so it's kind of just been put on hold for the foreseeable future.

I remember looking into getting the image to be set properly on the Appimage before (I use Arch Linux myself), but Tauri (the framework that this project uses for frontend and bundling the Appimage) doesn't seem to support it as far as I can tell :/

I was working on re-writing the project using `egui` for improved performance and more fine controls of the application (here is the repo for that: https://github.com/jlpatter/oxidized-git-2) but I haven't had too much time to work on that either and it hasn't caught up to this version in terms of functionality :/

I'll leave this issue open for now, but I wanted to warn you that I probably won't be able to get to it for the foreseeable future, sorry again.

**Comment by RAVENz46** [comment]
Thank you for responding.
egui version sounds great!
I'll wait patiently.

**Comment by RAVENz46** [comment]
@jlpatter 
Probably I found why it happens. I know you are busy and try to develop egui version, so you dont need to fix it. But let you know.
Now size of oxidized-git.png is 418x418 and place usr/share/icons/hicolor/418x418 inside of appimage. It may cause this issue. So, if icon size 256x256(or 512x512 also fine maybe?) it would work.
